[platformio]
default_envs = esp32

[env]
extra_scripts = pre:tools/pio_pre_hook.py, post:tools/pio_post_hook.py
lib_deps =
	adafruit/Adafruit GFX Library@^1.11.9
	adafruit/Adafruit ST7735 and ST7789 Library@^1.9.3

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
lib_extra_dirs = lib
upload_port = /dev/ttyACM0
upload_speed = 921600
monitor_speed = 115200
build_flags_old = -DFASTLED_SUPPORT -DI2C_SUPPORT -DSPI_SUPPORT -DUART_SUPPORT -DLCD_SUPPORT -DIPS_SUPPORT -DESP32_PICO_D4 -Ilib
