[platformio]
default_envs = T-Dongle-S3

[env]
extra_scripts = pre:tools/pio_pre_hook.py, post:tools/pio_post_hook.py

[env:T-Dongle-S3]
platform = espressif32
board = dongles3
framework = arduino
lib_extra_dirs = lib
upload_port = /dev/ttyACM0
upload_speed = 921600
monitor_speed = 115200
build_flags_old = -DDEBUG -DFASTLED -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1 -Ilib -DDONGLES3
